In [55]:
import pandas as pd
import numpy as np

In [56]:
mlbdata = pd.read_csv('rawmlbpitching.csv')
kbodata = pd.read_csv('rawkbopitching.csv')

In [57]:
mlbdata.head()

,year,teams,total_pitchers,average_age,runs_per_game,ERA,games_played,games_finished,complete_game,shutouts,...,wild_pitches,batters_faced,WHIP,BA_bip,hits_9,homeruns_9,walks_9,strikeouts_9,strikeout_walk,errors
0,2021,30,909,28.7,4.53,4.26,4858,4808,50,29,...,1862,181818,1.297,0.292,8.3,1.3,3.3,8.9,2.67,2626
1,2020,30,735,28.3,4.65,4.44,1796,1767,29,12,...,675,66506,1.327,0.292,8.4,1.3,3.5,9.1,2.56,1037
2,2019,30,831,28.4,4.83,4.49,4858,4813,45,26,...,1788,186517,1.334,0.298,8.7,1.4,3.3,8.9,2.69,2898
3,2018,30,799,28.4,4.45,4.14,4862,4820,42,19,...,1847,185139,1.304,0.296,8.5,1.2,3.2,8.5,2.63,2792
4,2017,30,755,28.5,4.65,4.35,4860,4801,59,27,...,1810,185295,1.342,0.300,8.8,1.3,3.3,8.3,2.53,2817

In [58]:
kbodata.head()

,year,team,average_age,runs_per_game,wins,losses,win_loss_percentage,ERA,run_average_9,games,...,hit_batter,balks,wild_pitches,batters_faced,WHIP,hits_9,homeruns_9,walks_9,strikeouts_9,strikeout_walk
0,2021,LG Twins,26.3,3.90,72,57,0.558,3.57,3.96,143,...,97,5.0,43.0,5416,1.312,8.0,0.6,3.9,7.6,1.96
1,2021,KT Wiz,28.4,4.06,75,59,0.560,3.67,4.17,143,...,42,1.0,56.0,5359,1.316,8.4,0.6,3.5,7.5,2.16
2,2021,Doosan Bears,27.5,4.57,70,65,0.519,4.28,4.66,143,...,73,7.0,51.0,5596,1.487,9.2,0.7,4.2,7.4,1.77
3,2021,Samsung Lions,28.8,4.57,75,59,0.560,4.29,4.70,143,...,51,3.0,56.0,5496,1.450,9.3,0.9,3.8,7.4,1.96
4,2021,NC Dinos,27.7,4.80,67,67,0.500,4.50,4.95,143,...,77,8.0,74.0,5575,1.476,9.1,0.9,4.2,7.5,1.79

In [59]:
print(mlbdata.describe())

              year  teams  total_pitchers  average_age  runs_per_game  \
count    22.000000   22.0       22.000000    22.000000       22.00000
mean   2010.500000   30.0      686.727273    28.581818        4.57500
std       6.493587    0.0       81.912951     0.251919        0.25812
min    2000.000000   30.0      591.000000    28.300000        4.07000
25%    2005.250000   30.0      632.750000    28.400000        4.39750
50%    2010.500000   30.0      663.000000    28.500000        4.61500
75%    2015.750000   30.0      735.000000    28.700000        4.76750
max    2021.000000   30.0      909.000000    29.200000        5.14000

             ERA  games_played  games_finished  complete_game   shutouts  ...  \
count  22.000000     22.000000       22.000000      22.000000  22.000000  ...
mean    4.255000   4719.545455     4589.590909     129.954545  53.863636  ...
std     0.247343    652.987547      632.970823      60.375395  20.709546  ...
min     3.740000   1796.000000     1767.000000      29.000000  12.000000  ...
25%     4.087500   4858.000000     4676.000000      88.250000  37.750000  ...
50%     4.295000   4858.000000     4717.000000     132.000000  61.000000  ...
75%     4.432500   4860.000000     4753.000000     171.000000  69.000000  ...
max     4.760000   4862.000000     4820.000000     234.000000  87.000000  ...

       wild_pitches  batters_faced       WHIP     BA_bip     hits_9  \
count     22.000000      22.000000  22.000000  22.000000  22.000000
mean    1586.772727  180672.636364   1.351818   0.297273   8.890909
std      244.911827   25573.268066   0.048602   0.002963   0.316091
min      675.000000   66506.000000   1.275000   0.292000   8.300000
25%     1503.000000  184653.250000   1.310750   0.295250   8.700000
50%     1567.000000  185922.500000   1.344500   0.297000   8.800000
75%     1752.500000  187356.500000   1.388250   0.299750   9.100000
max     1862.000000  190261.000000   1.468000   0.303000   9.400000

       homeruns_9    walks_9  strikeouts_9  strikeout_walk       errors
count   22.000000  22.000000     22.000000       22.000000    22.000000
mean     1.100000   3.268182      7.404545        2.277273  2904.136364
std      0.138013   0.205603      0.894681        0.319765   461.577656
min      0.900000   2.900000      6.400000        1.720000  1037.000000
25%      1.000000   3.125000      6.625000        2.002500  2831.250000
50%      1.100000   3.300000      7.100000        2.235000  2976.500000
75%      1.200000   3.375000      8.025000        2.575000  3065.250000
max      1.400000   3.800000      9.100000        2.690000  3447.000000

[8 rows x 32 columns]

In [60]:
print(kbodata.describe())

              year  average_age  runs_per_game        wins      losses  \
count   192.000000   192.000000     192.000000  192.000000  192.000000
mean   2011.078125    27.570833       4.875833   66.140625   66.130208
std       6.423871     1.397486       0.674857   11.228983   11.258445
min    2000.000000    23.800000       3.560000   35.000000   40.000000
25%    2005.750000    26.475000       4.360000   59.000000   57.000000
50%    2011.500000    27.550000       4.830000   66.500000   65.500000
75%    2017.000000    28.500000       5.340000   73.000000   74.000000
max    2021.000000    32.400000       6.950000   93.000000   97.000000

       win_loss_percentage         ERA  run_average_9       games  \
count           192.000000  192.000000     192.000000  192.000000
mean              0.500042    4.499740       4.946927  135.322917
std               0.079933    0.653634       0.702094    6.956100
min               0.265000    3.220000       3.580000  126.000000
25%               0.450000    4.002500       4.412500  128.000000
50%               0.500000    4.460000       4.890000  133.000000
75%               0.560000    4.972500       5.472500  144.000000
max               0.695000    6.350000       7.090000  144.000000

       games_started  ...  hit_batter       balks  wild_pitches  \
count     184.000000  ...  192.000000  184.000000    184.000000
mean      135.423913  ...   75.203125    3.902174     56.983696
std         7.089180  ...   16.905199    2.244896     15.775223
min       126.000000  ...   34.000000    0.000000     21.000000
25%       128.000000  ...   61.750000    2.000000     46.000000
50%       133.000000  ...   75.000000    4.000000     55.000000
75%       144.000000  ...   86.000000    5.000000     66.250000
max       144.000000  ...  120.000000   11.000000    103.000000

       batters_faced        WHIP      hits_9  homeruns_9     walks_9  \
count     192.000000  192.000000  192.000000  192.000000  192.000000
mean     5274.812500    1.444219    9.347917    0.916667    3.650521
std       327.937384    0.100631    0.716153    0.228662    0.475141
min      4612.000000    1.237000    7.600000    0.400000    2.600000
25%      5014.000000    1.368750    8.800000    0.700000    3.300000
50%      5199.500000    1.442000    9.300000    0.900000    3.600000
75%      5634.000000    1.513250    9.800000    1.100000    4.000000
max      5937.000000    1.761000   11.600000    1.500000    4.900000

       strikeouts_9  strikeout_walk
count    192.000000      192.000000
mean       6.633333        1.848594
std        0.709054        0.325589
min        5.000000        1.180000
25%        6.100000        1.607500
50%        6.700000        1.790000
75%        7.200000        2.052500
max        8.400000        2.820000

[8 rows x 32 columns]

In [61]:
team_counts = kbodata.groupby('year')['team'].nunique()
kbodata['teams'] = kbodata['year'].map(team_counts)

In [62]:
# Grouping the KBO data by 'year' and aggregating all columns
kbo_grouped_df = kbodata.groupby('year').agg({
    'average_age': 'mean',
    'runs_per_game': 'mean',
    'wins': 'sum',
    'losses': 'sum',
    'win_loss_percentage': 'mean',
    'ERA': 'mean',
    'run_average_9': 'mean',
    'games': 'sum',
    'games_started': 'sum',         
    'games_finished': 'sum',
    'complete_game': 'sum',
    'shutouts': 'sum',
    'saves': 'sum',
    'innings_pitched': 'sum',
    'hits': 'sum',
    'runs': 'sum',
    'earned_runs': 'sum',
    'home_runs': 'sum',
    'walks': 'sum',
    'intentional_walks': 'sum',
    'strikeouts': 'sum',
    'hit_batter': 'sum',
    'balks': 'sum',
    'wild_pitches': 'sum',
    'batters_faced': 'sum',
    'WHIP': 'mean',
    'hits_9': 'mean',
    'homeruns_9': 'mean',
    'walks_9': 'mean',
    'strikeouts_9': 'mean',
    'strikeout_walk': 'mean',
    'teams': 'max'  # Include the 'teams' column using 'max' to retain the unique count for each year
}).reset_index()

# Display the grouped data
print(kbo_grouped_df)

    year  average_age  runs_per_game  wins  losses  win_loss_percentage  \
0   2000    26.625000       4.897500   502     500             0.499875
1   2001    27.175000       5.175000   516     516             0.499500
2   2002    27.225000       4.636250   517     517             0.500875
3   2003    26.825000       4.635000   519     519             0.500250
4   2004    26.825000       4.690000   508     508             0.499375
5   2005    26.687500       4.590000   494     494             0.500750
6   2006    26.987500       3.951250   494     494             0.499625
7   2007    27.475000       4.272500   492     492             0.500250
8   2008    27.450000       4.485000   504     504             0.500125
9   2009    26.687500       5.162500   522     522             0.500625
10  2010    27.212500       4.982500   522     522             0.500000
11  2011    27.425000       4.531250   522     522             0.500250
12  2012    28.475000       4.115000   517     517             0.499875
13  2013    28.477778       4.644444   565     565             0.499778
14  2014    28.900000       5.623333   569     569             0.500333
15  2015    28.580000       5.278000   715     715             0.500100
16  2016    28.150000       5.607000   713     713             0.500000
17  2017    28.410000       5.335000   709     709             0.499900
18  2018    28.090000       5.552000   714     714             0.499800
19  2019    27.530000       4.548000   713     713             0.499700
20  2020    27.380000       5.165000   707     707             0.500100
21  2021    27.120000       4.791000   665     665             0.500000

         ERA  run_average_9  games  games_started  ...  balks  wild_pitches  \
0   4.630000       5.102500   1064            0.0  ...    0.0           0.0
1   4.708750       5.250000   1064         1064.0  ...   26.0         406.0
2   4.238750       4.685000   1064         1064.0  ...   25.0         354.0
3   4.270000       4.707500   1064         1064.0  ...   25.0         361.0
4   4.293750       4.746250   1064         1064.0  ...   28.0         383.0
5   4.220000       4.660000   1008         1008.0  ...   22.0         365.0
6   3.582500       4.006250   1008         1008.0  ...   18.0         293.0
7   3.910000       4.300000   1008         1008.0  ...   31.0         330.0
8   4.117500       4.518750   1008         1008.0  ...   27.0         352.0
9   4.805000       5.237500   1064         1064.0  ...   23.0         424.0
10  4.586250       5.027500   1064         1064.0  ...   28.0         506.0
11  4.140000       4.586250   1064         1064.0  ...   33.0         503.0
12  3.821250       4.151250   1064         1064.0  ...   32.0         460.0
13  4.318889       4.686667   1152         1152.0  ...   40.0         530.0
14  5.215556       5.723333   1152         1152.0  ...   23.0         545.0
15  4.874000       5.348000   1440         1440.0  ...   47.0         754.0
16  5.172000       5.676000   1440         1440.0  ...   57.0         701.0
17  4.970000       5.412000   1440         1440.0  ...   45.0         709.0
18  5.173000       5.638000   1440         1440.0  ...   41.0         673.0
19  4.168000       4.616000   1440         1440.0  ...   39.0         594.0
20  4.759000       5.236000   1440         1440.0  ...   46.0         648.0
21  4.439000       4.903000   1430         1430.0  ...   62.0         594.0

    batters_faced      WHIP     hits_9  homeruns_9   walks_9  strikeouts_9  \
0           40338  1.444625   9.262500    1.087500  3.712500      6.587500
1           41960  1.508875   9.425000    1.025000  4.150000      6.137500
2           40986  1.360875   9.037500    1.062500  3.225000      6.900000
3           41152  1.413750   9.150000    1.000000  3.587500      5.812500
4           41351  1.418500   9.050000    0.912500  3.700000      6.225000
5           38976  1.383750   8.987500    0.875000  3.487500      6.437500
6           38091  1.315750   8.525000    0.687500  3.325000      5.925000
7           38995  1.386375   8.862500    0.700000  3.612500      5.625000
8           39018  1.407875   9.087500    0.650000  3.575000      5.762500
9           41864  1.507125   9.475000    1.100000  4.100000      6.612500
10          41597  1.446250   9.175000    0.925000  3.837500      6.662500
11          41068  1.409750   8.950000    0.737500  3.750000      6.662500
12          40527  1.344750   8.587500    0.587500  3.500000      6.325000
13          44893  1.435667   9.122222    0.722222  3.788889      6.811111
14          45853  1.559111  10.177778    1.011111  3.844444      6.766667
15          56742  1.490500   9.710000    1.070000  3.690000      7.420000
16          57614  1.556600  10.260000    1.060000  3.790000      6.860000
17          56882  1.480200  10.130000    1.100000  3.170000      7.060000
18          56903  1.493600  10.190000    1.240000  3.250000      7.540000
19          55627  1.400900   9.260000    0.700000  3.350000      6.740000
20          56643  1.475200   9.550000    0.980000  3.720000      6.940000
21          55684  1.458100   8.950000    0.810000  4.200000      7.240000

    strikeout_walk  teams
0         1.791250      8
1         1.482500      8
2         2.168750      8
3         1.645000      8
4         1.688750      8
5         1.861250      8
6         1.802500      8
7         1.577500      8
8         1.625000      8
9         1.633750      8
10        1.766250      8
11        1.802500      8
12        1.817500      8
13        1.808889      9
14        1.786667      9
15        2.053000     10
16        1.827000     10
17        2.234000     10
18        2.331000     10
19        2.051000     10
20        1.884000     10
21        1.747000     10

[22 rows x 33 columns]

In [63]:
print("Column names in the MLB dataset:")
for column in mlbdata:
    print(column)

Column names in the MLB dataset:
year
teams
total_pitchers
average_age
runs_per_game
ERA
games_played
games_finished
complete_game
shutouts
shutouts_team
saves
innings_pitched
hits
runs
earned_runs
home_runs
walks
intentional_walks
strikeouts
hit_batter
balks
wild_pitches
batters_faced
WHIP
BA_bip
hits_9
homeruns_9
walks_9
strikeouts_9
strikeout_walk
errors

In [64]:
print("Column names in the KBO dataset:")
for column in kbo_grouped_df.columns:
    print(column)

Column names in the KBO dataset:
year
average_age
runs_per_game
wins
losses
win_loss_percentage
ERA
run_average_9
games
games_started
games_finished
complete_game
shutouts
saves
innings_pitched
hits
runs
earned_runs
home_runs
walks
intentional_walks
strikeouts
hit_batter
balks
wild_pitches
batters_faced
WHIP
hits_9
homeruns_9
walks_9
strikeouts_9
strikeout_walk
teams

In [65]:
kbo_grouped_df = kbo_grouped_df.drop(columns = ['wins', 'losses', 'win_loss_percentage', 'run_average_9', 'games', 'games_started'])
mlbdata = mlbdata.drop(columns = ['total_pitchers', 'games_played', 'shutouts_team', 'BA_bip', 'errors'])

In [66]:
mlb_columns_order = mlbdata.columns.tolist()

# Identify and add missing columns to KBO dataset with NaN values
for col in mlb_columns_order:
    if col not in kbo_grouped_df.columns:
        kbo_grouped_df[col] = np.nan

# Reorder the KBO dataset columns to match the MLB dataset column order
kbo_grouped_df = kbo_grouped_df[mlb_columns_order]

# Display the reordered datasets
print("Reordered KBO Data:")
print(kbo_grouped_df.head())
print("\nReordered MLB Data:")
print(mlbdata.head())

Reordered KBO Data:
   year  teams  average_age  runs_per_game      ERA  games_finished  \
0  2000      8       26.625        4.89750  4.63000             0.0
1  2001      8       27.175        5.17500  4.70875          1022.0
2  2002      8       27.225        4.63625  4.23875          1026.0
3  2003      8       26.825        4.63500  4.27000          1029.0
4  2004      8       26.825        4.69000  4.29375          1035.0

   complete_game  shutouts  saves  innings_pitched  ...  hit_batter  balks  \
0             44        10    281           9187.1  ...         523    0.0
1             42        37    262           9440.0  ...         515   26.0
2             38        55    253           9482.7  ...         658   25.0
3             35        58    272           9432.6  ...         605   25.0
4             29        58    273           9463.8  ...         681   28.0

   wild_pitches  batters_faced      WHIP  hits_9  homeruns_9  walks_9  \
0           0.0          40338  1.444625  9.2625      1.0875   3.7125
1         406.0          41960  1.508875  9.4250      1.0250   4.1500
2         354.0          40986  1.360875  9.0375      1.0625   3.2250
3         361.0          41152  1.413750  9.1500      1.0000   3.5875
4         383.0          41351  1.418500  9.0500      0.9125   3.7000

   strikeouts_9  strikeout_walk
0        6.5875         1.79125
1        6.1375         1.48250
2        6.9000         2.16875
3        5.8125         1.64500
4        6.2250         1.68875

[5 rows x 27 columns]

Reordered MLB Data:
   year  teams  average_age  runs_per_game   ERA  games_finished  \
0  2021     30         28.7           4.53  4.26            4808
1  2020     30         28.3           4.65  4.44            1767
2  2019     30         28.4           4.83  4.49            4813
3  2018     30         28.4           4.45  4.14            4820
4  2017     30         28.5           4.65  4.35            4801

   complete_game  shutouts  saves  innings_pitched  ...  hit_batter  balks  \
0             50        29   1191          42615.0  ...        2112    155
1             29        12    422          15468.2  ...         821     63
2             45        26   1180          43423.1  ...        1984    153
3             42        19   1244          43489.0  ...        1922    151
4             59        27   1179          43257.0  ...        1763    155

   wild_pitches  batters_faced   WHIP  hits_9  homeruns_9  walks_9  \
0          1862         181818  1.297     8.3         1.3      3.3
1           675          66506  1.327     8.4         1.3      3.5
2          1788         186517  1.334     8.7         1.4      3.3
3          1847         185139  1.304     8.5         1.2      3.2
4          1810         185295  1.342     8.8         1.3      3.3

   strikeouts_9  strikeout_walk
0           8.9            2.67
1           9.1            2.56
2           8.9            2.69
3           8.5            2.63
4           8.3            2.53

[5 rows x 27 columns]

In [91]:
cleaned_mlb_data = mlbdata.sort_values(by='year', ascending=True).reset_index(drop = True)
cleaned_kbo_data = kbo_grouped_df.reset_index(drop = True)

In [92]:
cleaned_mlb_data.to_csv('cleaned_mlb_data.csv', index=False)
cleaned_kbo_data.to_csv('cleaned_kbo_data.csv', index=False)

In [93]:
from IPython.display import FileLink

display(FileLink('cleaned_mlb_data.csv'))
display(FileLink('cleaned_kbo_data.csv'))

/Users/cmw/Desktop/mlb_vs_kbo_pitching_comparison_project/cleaned_mlb_data.csv

/Users/cmw/Desktop/mlb_vs_kbo_pitching_comparison_project/cleaned_kbo_data.csv